# -*- coding: utf-8 -*-
#
# This file is part of Flask-IIIF
# Copyright (C) 2014, 2015, 2016, 2017 CERN.
#
# Flask-IIIF is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

# Travis CI file, that integrates with coveralls for reporting test coverage.

language: python

cache:
  - pip

services:
  - redis-server

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release

python:
  - "2.7"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install coveralls pydocstyle requirements-builder"
  - "travis_retry pip install pytest pytest-pep8 pytest-cov pytest-cache"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

notifications:
  email: false

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "Oz5MXWgL+vP+6/JdG0S9RRsftPhGsl3COp+ijzagnK1vkYvhAMbd9SZG10TNBadiOVR0pQZ1ikqOsyQwRxd9m2QYM7pMCl6fRFlPox+O6rdIRhl+VEHGswBMH/GNoQYEvn+4Nt/BdTnTxwZLybBWv3YuYbhdvynmEOSaqyXn6GE="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    conditions: $REQUIREMENTS = release
